### ISSUE TITLE
Problem Statement Documentation Review

### ISSUE THREAD

**Issue by adrian-soch** [adrian-soch/attitude_check#4]
**Describe the request**
@smiths, Problem statement is ready for review.

**List the files**

- [Problem statement pdf](https://github.com/adrian-soch/attitude_check/blob/ca5ac08660b3ee82c9da75da2ba1467dd8e7b508/docs/ProblemStatementAndGoals/ProblemStatement.pdf)
- [Problem statement tex](https://github.com/adrian-soch/attitude_check/blob/584ef8934129a4c10bc9a5efd7eec7f5f7ad9baf/docs/ProblemStatementAndGoals/ProblemStatement.tex)

**Comment by smiths** [comment]
Feedback:

- excellent use of citation to credit Bing Chat
- the notation for your equation looks a little busy.  You might consider using a bold font to indicate a vector, rather than the arrow overtop.  You might also want shorter names, like a for accel.  Having said that, you should follow the conventions of the community.
- there isn't any theory given for the output.  It would be nice to see something of the math that connects the inputs to the output, or at least to see a link or citation for that information.  It is difficult to judge whether the scope of the project is appropriate without that information.  However, we can adjust the scope as we go along, so this isn't a problem at the moment.
- Ideally your software will work on a Mac, since that is my preferred testing environment.  :smile:

Your project looks great.  I'm looking forward to it.

Your project is approved.
